name: Build APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch: # 这个选项能让你在网页上点按钮直接触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 使用这个更稳定的 Action 替代掉报错的那个
      - name: Buildozer Action
        uses: Enteee/buildozer-action@v1.2.2
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CyberLife-APK
          path: bin/*.apk
